# Author: Cavelle Benjamin

variables:
  DOMAIN: "thecb4.io"
  EMAIL: "cavelle@thecb4.io"

stages:
  - build-test
  - docs

swift_5_3_focal:
  image:
    name: swift:5.3-focal
    entrypoint: [""]
  stage: build-test
  script:
    - swift test --enable-test-discovery --enable-code-coverage --filter "^(?!.*MacOS).*$"
  only:
    - main

swift_5_3_bionic:
  image:
    name: swift:5.2-bionic
    entrypoint: [""]
  stage: build-test
  script:
    - swift test --enable-test-discovery --enable-code-coverage --filter "^(?!.*MacOS).*$"
  only:
    - main

swift_5_2_focal:
  image:
    name: swift:5.2-focal
    entrypoint: [""]
  stage: build-test
  script:
    - swift test --enable-test-discovery --enable-code-coverage --filter "^(?!.*MacOS).*$"
  only:
    - main

swift_5_2_bionic:
  image:
    name: swift:5.2-bionic
    entrypoint: [""]
  stage: build-test
  script:
    - swift test --enable-test-discovery --enable-code-coverage --filter "^(?!.*MacOS).*$"
  only:
    - main

pages:
  image:
    name: swift:5.3-focal
  stage: docs
  dependencies:
    - swift_5_3_focal
    - swift_5_3_bionic
    - swift_5_2_focal
    - swift_5_2_bionic
  before_script:
    - apt-get install make
  script:
    - export WORKDIR=$PWD
    - git clone https://github.com/SwiftDocOrg/swift-doc /tmp/swift-doc
    - cd /tmp/swift-doc
    - make install
    - cd $WORKDIR
    #- swift doc ./Sources --output docs/ --type html --module-name blanket --author "Cavelle Benjamin" --author-url https://thecb4.io --twitter-handle _thecb4 --git-repository https://github.com/thecb4/blanket
    - swift doc generate ./Sources --module-name Blanket --output docs --format html
    - mkdir public
    - mkdir public/Resources
    - cp docs/index.html public/index.html
    - cp Resources/logo.png public/Resources/logo.png
  artifacts:
    paths:
    - public
  only:
    - main

# wiki:
#   image:
#     name: swift:5.1.4-xenial
#   stage: docs
#   dependencies:
#     - spm_514_xenial
#   script:
#     - export WORKDIR=$PWD
#     - git clone https://github.com/yonaskolb/Mint.git /tmp/Mint
#     - cd /tmp/Mint
#     - swift run mint install yonaskolb/mint
#     - cd $WORKDIR
#     - mint install thecb4/swift-doc@main
#     - git rm --cached wiki
#     - git add wiki
#     - cd wiki
#     - rm -rf **/*.md
#     - cd ..
#     - swift doc ./Sources --output wiki
#     - git submodule foreach --recursive deinit -f --all -- wiki
#     - git add --all -f
#     - cd wiki
#     - git commit -m "Update docs"
#     - git push origin main
#   artifacts:
#     paths:
#     - wiki
#   only:
#     - main
