# Author: Cavelle Benjamin

variables:
  DOMAIN: "thecb4.io"
  EMAIL: "cavelle@thecb4.io"

stages:
  - build-test
  - docs

spm_514_xenial:
  image:
    name: swift:5.1.4-xenial
    entrypoint: [""]
  stage: build-test
  script:
    - swift package update
    - swift test --generate-linuxmain
    - swift test --enable-code-coverage --filter "^(?!.*MacOS).*$"
  only:
    - master

# pages:
#   image:
#     name: swift:5.1.4-xenial
#   stage: docs
#   dependencies:
#     - spm_514_xenial
#   script:
#     - export WORKDIR=$PWD
#     - git clone https://github.com/yonaskolb/Mint.git /tmp/Mint
#     - cd /tmp/Mint
#     - swift run mint install yonaskolb/mint
#     - cd $WORKDIR
#     - mint install thecb4/swift-doc@master
#     - swift doc ./Sources --output docs/ --type html --module-name blanket --author "Cavelle Benjamin" --author-url https://thecb4.io --twitter-handle _thecb4 --git-repository https://github.com/thecb4/blanket
#     - mkdir public
#     - mkdir public/Resources
#     - cp docs/index.html public/index.html
#     - cp Resources/logo.png public/Resources/logo.png
#   artifacts:
#     paths:
#     - public
#   only:
#     - master

wiki:
  image:
    name: swift:5.1.4-xenial
  stage: docs
  dependencies:
    - spm_514_xenial
  script:
    - export WORKDIR=$PWD
    - git clone https://github.com/yonaskolb/Mint.git /tmp/Mint
    - cd /tmp/Mint
    - swift run mint install yonaskolb/mint
    - cd $WORKDIR
    - mint install thecb4/swift-doc@master
    - git rm --cached wiki
    - git add wiki
    - cd wiki
    - rm -rf **/*.md
    - cd ..
    - swift doc ./Sources --output wiki
    - git submodule foreach --recursive deinit -f --all -- wiki
    - git add --all -f
    - cd wiki
    - git commit -m "Update docs"
    - git push origin master
  artifacts:
    paths:
    - wiki
  only:
    - master
