#if !canImport(ObjectiveC)
import XCTest

extension BlanketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BlanketTests = [
        ("testBlanketRunNoArgs", testBlanketRunNoArgs),
        ("testBlanketSimpleArgs", testBlanketSimpleArgs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BlanketTests.__allTests__BlanketTests),
    ]
}
#endif
