#if !canImport(ObjectiveC)
import XCTest

extension BlanketCLITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BlanketCLITests = [
        ("testCLIArgs", testCLIArgs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BlanketCLITests.__allTests__BlanketCLITests),
    ]
}
#endif
